on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: ' before printing folder'
        run: ls

      - uses: actions/checkout@v3
      - name: ' login to dockerr'
        run: docker login --username alaa942 --password mzaea1112
      